connected(alligatorpond,backdoor,2).
connected(backdoor,exit,1).
connected(bedroom,library,5).
connected(billiardroom,greenhouse,2).
connected(coatroom,servantroom,2).
connected(diningroom,alligatorpond,2).
connected(diningroom,kitchen,4).
connected(diningroom,library,7).
connected(entrance,mainhall,2).
connected(greenhouse,backdoor,5).
connected(kitchen,billiardroom,5).
connected(kitchen,greenhouse,1).
connected(library,billiardroom,3).
connected(mainhall,bedroom,4).
connected(mainhall,coatroom,3).
connected(mainhall,diningroom,3).
connected(mainhall,library,6).
connected(servantroom,alligatorpond,2).
connected(servantroom,diningroom,3).
